logging:
  level:
    com.github.rahmnathan: info

server:
  port: 8080
  ssl:
    enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

opentracing:
  jaeger:
    enabled: false

keycloak:
  enabled: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true