logging:
  level:
    com.github.rahmnathan: info

server:
  port: 8080
  ssl:
    enabled: false

spring:
  datasource:
    password: pw123
    url: "jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432/localmovies"
    username: localmovies
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: false

opentracing:
  jaeger:
    enabled: false

keycloak:
  enabled: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true